- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: check arch
  command: dpkg --print-architecture
  register: arch_res
  check_mode: no

- name: install dependencies
  become: yes
  apt:
    name:
      - build-essential
      - vim-nox
      - htop
      - dstat
      - tree
      - zsh
      - tmux
      - lsof
      - percona-toolkit

- name: set editor vim
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim
