- name: Create .ssh directory if it does not exist
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Put ~/.ssh/id_rsa
  copy:
    content: "{{vault_ssh_private_key}}"
    dest: ~/.ssh/id_rsa
    mode: '0600'
