name: Ansible CI

on:
  pull_request:
    paths:
      - "ansible/**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_password_private
        working-directory: ansible

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i test site.yml
